### ISSUE TITLE
Research RDFS

### ISSUE THREAD

**Issue by AbdBarho** [code-openness/Data#18]

**Comment by hannahtro** [comment]
**RDF (Research Description Framework):**
RDF is a method for modelling information. Statements about resources consist of triples: subject-predicate-object. In the diagram below the subject 'author' and the object 'human' are connected by the predicate 'is'.

![RDF_triple](https://user-images.githubusercontent.com/46645533/58867918-93e86c80-86bb-11e9-9050-7e8702bf23c8.jpeg)

RDF describes resources with classes, properties and values.

part of vocabulary in RDF:
**Classes**: rdf:Property (class of RDF properties)
![RDF_Property](https://user-images.githubusercontent.com/46645533/58869574-ce073d80-86be-11e9-8ad2-2def32b40e7e.jpg)


**Properties**: rdf:type (the subject is an instance of a class)
![RDF_type](https://user-images.githubusercontent.com/46645533/58868286-4ae4e800-86bc-11e9-9f33-3f78020c6249.png)

**RDFS (RDF Schema):** 
RDFS provides vocabulary to model information of a specific application domain. All schema information in RDFS is defined by RDF triples. 

part of vocabulary in RDFS: 
**Classes**: rdfs:Class (class of classes)
![RDFS_Class](https://user-images.githubusercontent.com/46645533/58869190-08240f80-86be-11e9-900a-a1a5e11d9cf9.jpg)

**Properties**: rdfs:subClassOf (subject is subclass of a class), rdfs:subPropertyOf (subject is subproperty of property), rdfs:domain (domain of subject property), rdfs:range (range of subject property)
![RDFS_subClassOf](https://user-images.githubusercontent.com/46645533/58870108-d449e980-86bf-11e9-9490-0cdb2f24fcd1.jpg)

![RDFS_subPropteryOf](https://user-images.githubusercontent.com/46645533/58870279-34d92680-86c0-11e9-925e-60f3fdbeed8c.jpg)

![RDFS_domain](https://user-images.githubusercontent.com/46645533/58868855-71efe980-86bd-11e9-976e-c6b6d1abb2fb.jpg)

![RDFS_range](https://user-images.githubusercontent.com/46645533/58870950-70282500-86c1-11e9-92a2-2053d67b7b82.png)

! Classes are used to construct types of objects. Properties are used to describe objects. 
(complete list of RDF classes and RDF properties: https://www.w3.org/TR/rdf-schema/#ch_property)

**Concept of inference**: extracting more about the data than what is explicitly expressed in data
From "A rdfs:SubclassOf B" and "r rdf:type A" follows "r rdf:type B"

Using **hierarchy** of related properties in order to introduce specificity:
From "P rdfs:subPropertyOf R" and "A P B" follows "A R B"
