### ISSUE TITLE
check OpenRefine and the possibility to use it for our data

### ISSUE THREAD

**Issue by AbdBarho** [code-openness/Data#31]
[`OpenRefine.org`](http://openrefine.org/)

**Comment by kozae** [comment]
Open Refine has built in features for detecting similar entities that are written in different ways. Different implementation of "Edit Distance" are present.
There are also some extensions for interaction with Wikidata, but I am not sure of their potential, colleagues who has more contact with Wikidata should look into that.
Otherwise, Open Refine has also the possibility to write python code to perform filtering on the column, but basically it is the same things we were able to do with Pandas.
